#!/bin/bash

OUT='all.h'

echo "generating ${OUT}"

DIR=$(dirname ${BASH_SOURCE[0]})
cd "${DIR}"

echo "#pragma once
// WARNING: this file is generated by gen_all.sh
" > $OUT

find engine/ | \
    egrep '\.(h|hpp)$' | \
    egrep -v '/(all.h|dummy.cpp)$' | \
    egrep -v 'freetype' | \
    egrep -v 'glm/(core|test)/' | \
    xargs printf "#include <%s>\n" >> $OUT

echo "#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <unordered_map>
#include <map>
#include <queue>
#include <list>
#include <set>" >> $OUT
